### PR TITLE
Update formula to release v1.8.0

### PR DESCRIPTION
**Pull request by nak3**
/cc @lionelvillard @dsimansk

Created this PR based on https://github.com/knative/homebrew-client/pull/73

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
Can you merge my PR first? 

#80 

/hold

**Comment by dsimansk** [comment]
@nak3 can you please reset on `main` and then `CURRENT_RELEASE=1.8.0 PREVIOUS_RELEASE=1.7.0 ./hack/update-versions.sh` should do the trick.

**Comment by dsimansk** [comment]
Or I can just open a new PR. Just let me know. Thanks!

**Comment by nak3** [comment]
@dsimansk Thank you so much! It would be great if you could send the PR :pray:

**Comment by dsimansk** [comment]
> @dsimansk Thank you so much! It would be great if you could send the PR 🙏

Sure, np. 

Superseded by https://github.com/knative/homebrew-client/pull/82

/close

**Comment by dsimansk** [comment]
I'll update release manual with the new script reference.

**Pull request closed without merging**
