### PR TITLE
Add knative-release-leads to OWNERS

### PR DESCRIPTION
**Pull request by evankanderson**
Enable release leads to merge go mod changes, etc

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Review by maximilien — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Comment by dprotaso** [comment]
there's no OWNER_ALIASES file here

**Comment by rhuss** [comment]
closed in favor of #33

**Pull request closed without merging**
