### PR TITLE
Update kn to v1.13

### PR DESCRIPTION
**Pull request by dsimansk**
Per title update homebrew config to new release.

Generated by:
```
CURRENT_RELEASE=1.13.0 PREVIOUS_RELEASE=1.12.0 ./hack/update-versions.sh
```

/cc @knative/knative-release-leads

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by skonto** [comment]
/lgtm
@dsimansk how do you generate/verify this?

**Comment by dsimansk** [comment]
> Out of curiosity @dsimansk how do you generate/verify this?
There is a simple generate script in `hack/` and then it's testable as local tap file. Definitely it can be a GH action.
```
➜  homebrew-client git:(pr/release-1.13) brew unlink kn
➜  homebrew-client git:(pr/release-1.13) brew install ./kn.rb --force
```

**Comment by dsimansk** [comment]
The verification part is partially started here. It can be used as an inspiration/base to finish it. TBH I've forgotten about that  PR. It can be certainly revived. 

https://github.com/knative-extensions/homebrew-kn-plugins/pull/158

**Pull request merged**
